artifact_uri: file:C:/code_py/MyProjects/Project3/akinluaayomide8/443585732958131951/63e36d5ce40b4ed4b1e39d1c1df70d3a/artifacts
end_time: 1764974003585
entry_point_name: ''
experiment_id: '443585732958131951'
lifecycle_stage: active
run_id: 63e36d5ce40b4ed4b1e39d1c1df70d3a
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1764973938095
status: 3
tags: []
user_id: akinluaayomide8
